In [145]:
import pandas as pd

In [146]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [147]:
movies=pd.read_csv('dataset.csv')
movies.head()

,Id,Title,Genres,Popularity,Release Date,Original Language,Vote Average,Vote Count,Overview
0,155,The Dark Knight,"['Drama', 'Action', 'Crime', 'Thriller']",82.214,2008-07-14,en,8.510,30011,Batman raises the stakes in his war on crime. ...
1,122,The Lord of the Rings: The Return of the King,"['Adventure', 'Fantasy', 'Action']",74.454,2003-12-01,en,8.477,21810,Aragorn is revealed as the heir to the ancient...
2,569094,Spider-Man: Across the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ...",1648.384,2023-05-31,en,8.530,2110,"After reuniting with Gwen Stacy, Brooklynâ€™s ..."
3,27205,Inception,"['Action', 'Science Fiction', 'Adventure']",86.087,2010-07-15,en,8.363,33958,"Cobb, a skilled thief who commits corporate es..."
4,120,The Lord of the Rings: The Fellowship of the Ring,"['Adventure', 'Fantasy', 'Action']",91.459,2001-12-18,en,8.400,22920,"Young hobbit Frodo Baggins, after inheriting a..."

In [148]:
movies.describe()

                 Id   Popularity  Vote Average    Vote Count
count  2.424000e+03  2424.000000   2424.000000   2424.000000
mean   1.445358e+05    39.923460      7.069005   3293.403465
std    2.261117e+05   163.406766      1.121598   4475.363676
min    1.100000e+01     0.600000      0.000000      0.000000
25%    3.671000e+03    11.080750      6.804000    631.000000
50%    1.283000e+04    17.325000      7.202500   1492.500000
75%    2.497090e+05    31.149000      7.597000   3900.750000
max    1.130515e+06  3963.447000     10.000000  33958.000000

In [149]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 2424 entries, 0 to 2423
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 2424 non-null   int64
 1   Title              2424 non-null   str
 2   Genres             2424 non-null   str
 3   Popularity         2424 non-null   float64
 4   Release Date       2419 non-null   str
 5   Original Language  2424 non-null   str
 6   Vote Average       2424 non-null   float64
 7   Vote Count         2424 non-null   int64
 8   Overview           2422 non-null   str
dtypes: float64(2), int64(2), str(5)
memory usage: 170.6 KB

In [150]:
movies.isnull().sum()

Id                   0
Title                0
Genres               0
Popularity           0
Release Date         5
Original Language    0
Vote Average         0
Vote Count           0
Overview             2
dtype: int64

In [151]:
movies.columns

Index(['Id', 'Title', 'Genres', 'Popularity', 'Release Date',
       'Original Language', 'Vote Average', 'Vote Count', 'Overview'],
      dtype='str')

In [152]:
#our recommeder systen does not need orginal language ,release date ,popularity ,vote avg and vote count 
#  so we will drop these columns

#we need only movie id, title ,genre, overview

In [153]:
#movies=movies.drop(columnts =['original_language','release_date','popularity','vote_average','vote_count'],axis=1)

In [154]:
movies=movies[['Id','Title','Genres','Overview']]

In [155]:
movies.head()

,Id,Title,Genres,Overview
0,155,The Dark Knight,"['Drama', 'Action', 'Crime', 'Thriller']",Batman raises the stakes in his war on crime. ...
1,122,The Lord of the Rings: The Return of the King,"['Adventure', 'Fantasy', 'Action']",Aragorn is revealed as the heir to the ancient...
2,569094,Spider-Man: Across the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ...","After reuniting with Gwen Stacy, Brooklynâ€™s ..."
3,27205,Inception,"['Action', 'Science Fiction', 'Adventure']","Cobb, a skilled thief who commits corporate es..."
4,120,The Lord of the Rings: The Fellowship of the Ring,"['Adventure', 'Fantasy', 'Action']","Young hobbit Frodo Baggins, after inheriting a..."

In [156]:
#merging genres and overview to crete column called tag

In [157]:
movies['tags']=movies['Genres']+' '+movies['Overview']
movies.head()

,Id,Title,Genres,Overview,tags
0,155,The Dark Knight,"['Drama', 'Action', 'Crime', 'Thriller']",Batman raises the stakes in his war on crime. ...,"['Drama', 'Action', 'Crime', 'Thriller'] Batma..."
1,122,The Lord of the Rings: The Return of the King,"['Adventure', 'Fantasy', 'Action']",Aragorn is revealed as the heir to the ancient...,"['Adventure', 'Fantasy', 'Action'] Aragorn is ..."
2,569094,Spider-Man: Across the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ...","After reuniting with Gwen Stacy, Brooklynâ€™s ...","['Action', 'Adventure', 'Animation', 'Science ..."
3,27205,Inception,"['Action', 'Science Fiction', 'Adventure']","Cobb, a skilled thief who commits corporate es...","['Action', 'Science Fiction', 'Adventure'] Cob..."
4,120,The Lord of the Rings: The Fellowship of the Ring,"['Adventure', 'Fantasy', 'Action']","Young hobbit Frodo Baggins, after inheriting a...","['Adventure', 'Fantasy', 'Action'] Young hobbi..."

In [158]:
movies=movies.drop(columns=['Genres','Overview'])
movies.head()

,Id,Title,tags
0,155,The Dark Knight,"['Drama', 'Action', 'Crime', 'Thriller'] Batma..."
1,122,The Lord of the Rings: The Return of the King,"['Adventure', 'Fantasy', 'Action'] Aragorn is ..."
2,569094,Spider-Man: Across the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ..."
3,27205,Inception,"['Action', 'Science Fiction', 'Adventure'] Cob..."
4,120,The Lord of the Rings: The Fellowship of the Ring,"['Adventure', 'Fantasy', 'Action'] Young hobbi..."

In [159]:
# text data -- nlp concepts 
#2 ways : bag of words and tfidf vectorizer

we using BOW

In production recommender systems they often try multiple approaches:

Bag of Words
TF-IDF
Word2Vec
BERT embeddings

Then compare similarity results

In [160]:
from sklearn.feature_extraction.text import CountVectorizer
#to convert text into vector
cv=CountVectorizer(max_features=5000 ,stop_words='english')
cv.fit_transform(movies['tags'].astype('U')).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2424, 5000))

In [161]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=5000,stop_words='english')
vector=tfidf.fit_transform(movies['tags'].values.astype('U')).toarray()
vector

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(2424, 5000))

In [162]:
from sklearn.metrics.pairwise import cosine_similarity
sim=cosine_similarity(vector)
sim

array([[1.        , 0.00546308, 0.00448245, ..., 0.00364324, 0.02348473,
        0.        ],
       [0.00546308, 1.        , 0.02833291, ..., 0.01382365, 0.01249583,
        0.01151486],
       [0.00448245, 0.02833291, 1.        , ..., 0.05194813, 0.        ,
        0.01770974],
       ...,
       [0.00364324, 0.01382365, 0.05194813, ..., 1.        , 0.01949842,
        0.01796772],
       [0.02348473, 0.01249583, 0.        , ..., 0.01949842, 1.        ,
        0.05321066],
       [0.        , 0.01151486, 0.01770974, ..., 0.01796772, 0.05321066,
        1.        ]], shape=(2424, 2424))

In [163]:
movies['Title'].values[2]

'Spider-Man: Across the Spider-Verse'

In [164]:
movies[movies['Title']=='The Dark Knight Rises']

,Id,Title,tags
20,49026,The Dark Knight Rises,"['Action', 'Crime', 'Drama', 'Thriller'] Follo..."

In [165]:
movies[movies['Title']=='The Dark Knight Rises'].index[0]

20

In [166]:
sim[2]

array([0.00448245, 0.02833291, 1.        , ..., 0.05194813, 0.        ,
       0.01770974], shape=(2424,))

In [167]:
#ab isko enumerate krdenge kyuki we want to find top 5 results ,enumerate isko sbke sath iterate krdeg
sorted(list (enumerate(sim[2])),reverse=True)
#here sorting is basd on index [0]
sorted(list(enumerate(sim[2])),reverse=True,key=lambda x:x[1])
#now it will sort by index[1] jo ki sim_score h

[(2, np.float64(1.0)),
 (17, np.float64(0.42270488818560925)),
 (287, np.float64(0.20637643102698372)),
 (38, np.float64(0.17411871256445144)),
 (2187, np.float64(0.15608125533549166)),
 (111, np.float64(0.12345426565212533)),
 (293, np.float64(0.12312550570432182)),
 (2296, np.float64(0.11973000030910241)),
 (769, np.float64(0.10859863818609797)),
 (836, np.float64(0.10462848651524495)),
 (763, np.float64(0.10433043099675286)),
 (631, np.float64(0.10258126468610797)),
 (564, np.float64(0.10150576379036373)),
 (137, np.float64(0.1006448370789942)),
 (831, np.float64(0.09802065842437375)),
 (1599, np.float64(0.09788615689788366)),
 (21, np.float64(0.09709797093080809)),
 (36, np.float64(0.09577469442737814)),
 (82, np.float64(0.09577469442737814)),
 (1650, np.float64(0.09577469442737814)),
 (104, np.float64(0.09488391758547611)),
 (1785, np.float64(0.09420123445255507)),
 (783, np.float64(0.09359606245812255)),
 (1378, np.float64(0.09008092308994009)),
 (367, np.float64(0.08968396095087103)),
 (682, np.float64(0.08875435234021448)),
 (2268, np.float64(0.08826896802313193)),
 (339, np.float64(0.08700151546469956)),
 (146, np.float64(0.08695470539784354)),
 (878, np.float64(0.08660462553472556)),
 (2374, np.float64(0.08566009012062109)),
 (205, np.float64(0.0836328798979082)),
 (127, np.float64(0.0833601303573149)),
 (419, np.float64(0.08319481966845454)),
 (109, np.float64(0.08252045240836758)),
 (2261, np.float64(0.0815791525137118)),
 (434, np.float64(0.08082391537895411)),
 (399, np.float64(0.08074316308091613)),
 (775, np.float64(0.08063269294747966)),
 (943, np.float64(0.07944470218304789)),
 (80, np.float64(0.07911441967261668)),
 (771, np.float64(0.07830856704781305)),
 (1316, np.float64(0.07752942933400132)),
 (2171, np.float64(0.07718093881882666)),
 (2401, np.float64(0.07713115807189934)),
 (135, np.float64(0.07532150270694717)),
 (425, np.float64(0.07477165786013404)),
 (1324, np.float64(0.07451619679218659)),
 (169, np.float64(0.07427019390781689)),
 (1390, np.float64(0.07426108015524552)),
 (473, np.float64(0.07400837567145527)),
 (2032, np.float64(0.07364509227835474)),
 (870, np.float64(0.07360062312733173)),
 (1381, np.float64(0.07342768530613636)),
 (243, np.float64(0.07321163078448052)),
 (948, np.float64(0.07317617092388919)),
 (392, np.float64(0.07292212769524922)),
 (199, np.float64(0.07237439118592201)),
 (1438, np.float64(0.07200411105974709)),
 (797, np.float64(0.07192255102010464)),
 (1940, np.float64(0.07062072749146962)),
 (67, np.float64(0.07046803799105134)),
 (1665, np.float64(0.06973822481091212)),
 (826, np.float64(0.06972634632152203)),
 (1432, np.float64(0.06962037590088689)),
 (321, np.float64(0.06928636148167869)),
 (394, np.float64(0.06883481734939091)),
 (28, np.float64(0.06873550401237369)),
 (867, np.float64(0.0681056741707957)),
 (105, np.float64(0.06670902441583153)),
 (2333, np.float64(0.06665192275345787)),
 (1074, np.float64(0.0663487771656453)),
 (2244, np.float64(0.06555545323792913)),
 (1041, np.float64(0.06524676356528286)),
 (147, np.float64(0.0648190043212077)),
 (1280, np.float64(0.06481422901414437)),
 (2222, np.float64(0.06439172426722715)),
 (567, np.float64(0.06409971226714148)),
 (2242, np.float64(0.06346401784394798)),
 (2175, np.float64(0.06334811532525587)),
 (2189, np.float64(0.06288335781696114)),
 (84, np.float64(0.062155114434553925)),
 (85, np.float64(0.06204107545776951)),
 (924, np.float64(0.061770529480640525)),
 (2353, np.float64(0.06171144643561759)),
 (107, np.float64(0.061416495067765975)),
 (208, np.float64(0.06136070504803391)),
 (916, np.float64(0.06104118536733524)),
 (837, np.float64(0.06074791081674882)),
 (868, np.float64(0.060707905533714766)),
 (2135, np.float64(0.060262702921511986)),
 (195, np.float64(0.06002696005386322)),
 (514, np.float64(0.06000180661093507)),
 (470, np.float64(0.05987992460227665)),
 (557, np.float64(0.059515090677747184)),
 (110, np.float64(0.05942208819892513)),
 (910, np.float64(0.05940627463766103)),
 (832, np.float64(0.05915793557598185)),
 (1738, np.float64(0.05906403741879212)),
 (1351, np.float64(0.05901492807331662)),
 (2207, np.float64(0.05871738214980495)),
 (2340, np.float64(0.05848719918263378)),
 (579, np.float64(0.058236606002559824)),
 (873, np.float64(0.05805039866571438)),
 (922, np.float64(0.05796393696084192)),
 (2338, np.float64(0.057618559056188415)),
 (923, np.float64(0.057110132926541206)),
 (1548, np.float64(0.05695240044483488)),
 (334, np.float64(0.05694857007386858)),
 (201, np.float64(0.05678500416333199)),
 (6, np.float64(0.0560244666570259)),
 (44, np.float64(0.05600444422777373)),
 (887, np.float64(0.05591718590554773)),
 (747, np.float64(0.05557724159097516)),
 (2106, np.float64(0.05500735877250657)),
 (433, np.float64(0.05498750942067316)),
 (1215, np.float64(0.054888249839931486)),
 (609, np.float64(0.054803448647667945)),
 (176, np.float64(0.054719911451058666)),
 (60, np.float64(0.05470163693568977)),
 (1055, np.float64(0.054464436721753516)),
 (2136, np.float64(0.054387352336840944)),
 (404, np.float64(0.054361558190708884)),
 (893, np.float64(0.054212492804574686)),
 (1434, np.float64(0.05383290802102995)),
 (299, np.float64(0.05374529360006924)),
 (944, np.float64(0.05369751809530112)),
 (678, np.float64(0.053627453011531025)),
 (1890, np.float64(0.05344163813372638)),
 (315, np.float64(0.05343723351325714)),
 (890, np.float64(0.0533962017719211)),
 (258, np.float64(0.053241826594435215)),
 (1044, np.float64(0.05315944825857197)),
 (342, np.float64(0.05315768140997309)),
 (45, np.float64(0.05302132015239579)),
 (2192, np.float64(0.0528743754770715)),
 (2218, np.float64(0.052810870696977305)),
 (876, np.float64(0.05277357097675789)),
 (852, np.float64(0.05270203119069746)),
 (1430, np.float64(0.052574558793419414)),
 (762, np.float64(0.05256623844996276)),
 (2111, np.float64(0.05238825715456884)),
 (499, np.float64(0.052037419211097176)),
 (2421, np.float64(0.051948125002921466)),
 (303, np.float64(0.05191514787324913)),
 (958, np.float64(0.051698900036783686)),
 (2174, np.float64(0.05126500821105858)),
 (732, np.float64(0.05122530786868892)),
 (839, np.float64(0.05100845433691641)),
 (904, np.float64(0.0509572642535118)),
 (210, np.float64(0.05087211822853016)),
 (51, np.float64(0.05075847410140618)),
 (2212, np.float64(0.05067434725206414)),
 (1902, np.float64(0.05059962050124527)),
 (858, np.float64(0.050439068583656196)),
 (81, np.float64(0.0501875587899754)),
 (505, np.float64(0.05011783376275443)),
 (582, np.float64(0.05007682987070104)),
 (877, np.float64(0.050069922713584764)),
 (449, np.float64(0.049967175610114406)),
 (115, np.float64(0.04986595260525441)),
 (2210, np.float64(0.049699695598461956)),
 (730, np.float64(0.049604639189974827)),
 (2362, np.float64(0.04954124715524199)),
 (138, np.float64(0.04953919512649177)),
 (941, np.float64(0.049297634099414143)),
 (1551, np.float64(0.04912731453139334)),
 (625, np.float64(0.048900093650845855)),
 (112, np.float64(0.04879054551809508)),
 (150, np.float64(0.04850711809986496)),
 (2346, np.float64(0.04847934634794192)),
 (1294, np.float64(0.04847376673100105)),
 (2160, np.float64(0.04845036838996667)),
 (2417, np.float64(0.048237336891699116)),
 (753, np.float64(0.04821612238551547)),
 (681, np.float64(0.04795822785739676)),
 (712, np.float64(0.04793196295129751)),
 (587, np.float64(0.04784903992678496)),
 (768, np.float64(0.047604998366222034)),
 (368, np.float64(0.04744405311174785)),
 (2383, np.float64(0.047420565389579505)),
 (337, np.float64(0.04703686119455225)),
 (801, np.float64(0.04698095623598305)),
 (739, np.float64(0.046889225773020474)),
 (285, np.float64(0.04686499439402284)),
 (1761, np.float64(0.04677717492165489)),
 (351, np.float64(0.04660151797726133)),
 (1669, np.float64(0.04655466570689602)),
 (1051, np.float64(0.046269819120105804)),
 (1165, np.float64(0.04618543133997923)),
 (396, np.float64(0.04600181848239708)),
 (1448, np.float64(0.04591580802077934)),
 (866, np.float64(0.04590894023460705)),
 (140, np.float64(0.045814204330908374)),
 (1097, np.float64(0.04575508126889015)),
 (2161, np.float64(0.04565076792902553)),
 (2382, np.float64(0.045589227430047695)),
 (534, np.float64(0.04551538498957184)),
 (2243, np.float64(0.045473064290765766)),
 (10, np.float64(0.04547065275403345)),
 (623, np.float64(0.045413676085289956)),
 (693, np.float64(0.04536302110227714)),
 (1672, np.float64(0.04535637397673082)),
 (48, np.float64(0.045346257975133954)),
 (1987, np.float64(0.04529775603169904)),
 (905, np.float64(0.045256974174260466)),
 (825, np.float64(0.04520031996948967)),
 (24, np.float64(0.044983425475480364)),
 (930, np.float64(0.04495404838897809)),
 (398, np.float64(0.044816360322355)),
 (1834, np.float64(0.04481371628174633)),
 (729, np.float64(0.044787544216534296)),
 (527, np.float64(0.04469176837406167)),
 (106, np.float64(0.04462611230865297)),
 (1098, np.float64(0.044620565388637984)),
 (942, np.float64(0.044531344422283355)),
 (484, np.float64(0.04450407844468626)),
 (220, np.float64(0.04436333443148553)),
 (1477, np.float64(0.044360725535437)),
 (2350, np.float64(0.04410844758339629)),
 (2324, np.float64(0.04399455810012627)),
 (196, np.float64(0.04397718760093435)),
 (50, np.float64(0.04396812592031591)),
 (1699, np.float64(0.04375287591789744)),
 (929, np.float64(0.0435978521302528)),
 (842, np.float64(0.04357735467523215)),
 (88, np.float64(0.043545504104646075)),
 (1549, np.float64(0.04345848845457128)),
 (162, np.float64(0.04336221136248647)),
 (1562, np.float64(0.04333904232453799)),
 (1300, np.float64(0.04324277599071096)),
 (946, np.float64(0.04318701218207186)),
 (319, np.float64(0.04317710492093854)),
 (770, np.float64(0.04317710492093854)),
 (326, np.float64(0.043149433394978606)),
 (1288, np.float64(0.04303512100622806)),
 (926, np.float64(0.04302835878037661)),
 (850, np.float64(0.043014737488516544)),
 (1205, np.float64(0.04289547698317341)),
 (68, np.float64(0.04277919311965528)),
 (474, np.float64(0.04271567327129055)),
 (320, np.float64(0.04269085278607046)),
 (1214, np.float64(0.042665689709938406)),
 (2370, np.float64(0.042513008581844106)),
 (386, np.float64(0.04249476830151794)),
 (738, np.float64(0.04244957792520332)),
 (200, np.float64(0.04244427799855515)),
 (599, np.float64(0.042370030093632875)),
 (1105, np.float64(0.04233402611439683)),
 (1679, np.float64(0.04225011587594311)),
 (2236, np.float64(0.0422475122314532)),
 (776, np.float64(0.04223111262319275)),
 (822, np.float64(0.042157312430969214)),
 (2011, np.float64(0.04210289607944775)),
 (1682, np.float64(0.04186758471398389)),
 (225, np.float64(0.04183443162066258)),
 (357, np.float64(0.04178948647895059)),
 (745, np.float64(0.041757201142209245)),
 (517, np.float64(0.0417367847372472)),
 (310, np.float64(0.041716903174522264)),
 (1213, np.float64(0.04170632111405538)),
 (674, np.float64(0.041622280442562144)),
 (2406, np.float64(0.041537849728053945)),
 (895, np.float64(0.04144240879376044)),
 (465, np.float64(0.041265720428236924)),
 (1496, np.float64(0.041191322060716046)),
 (2371, np.float64(0.04118948722001767)),
 (945, np.float64(0.041104475922760814)),
 (343, np.float64(0.04107761881891769)),
 (1657, np.float64(0.041045152613817255)),
 (284, np.float64(0.04097116955929334)),
 (1070, np.float64(0.04091062398697601)),
 (350, np.float64(0.04090279320903565)),
 (354, np.float64(0.04072950180871862)),
 (1568, np.float64(0.04067333279089853)),
 (2375, np.float64(0.040590467782270365)),
 (750, np.float64(0.040521964873863406)),
 (229, np.float64(0.040484719621951645)),
 (95, np.float64(0.04047871021267372)),
 (446, np.float64(0.04047501645966187)),
 (448, np.float64(0.040474724159618)),
 (61, np.float64(0.0404598831057969)),
 (1691, np.float64(0.0404230060743791)),
 (1373, np.float64(0.040382420751178504)),
 (1200, np.float64(0.04016264931206059)),
 (854, np.float64(0.040034166017709275)),
 (892, np.float64(0.03996069770242243)),
 (391, np.float64(0.03988744301694453)),
 (388, np.float64(0.03966632453997601)),
 (1372, np.float64(0.03965796542709422)),
 (1033, np.float64(0.03955413860138434)),
 (189, np.float64(0.03934771109642744)),
 (2323, np.float64(0.03927443811278744)),
 (2264, np.float64(0.03918627931242566)),
 (2013, np.float64(0.03917887073340489)),
 (325, np.float64(0.03915512350280944)),
 (149, np.float64(0.038965113166676744)),
 (401, np.float64(0.03870964365329297)),
 (2337, np.float64(0.03861279964026738)),
 (2211, np.float64(0.038496350460322)),
 (2195, np.float64(0.03844079480498251)),
 (3, np.float64(0.03843225568176534)),
 (27, np.float64(0.038353923813477304)),
 (727, np.float64(0.038306549136609996)),
 (2172, np.float64(0.038291848478879904)),
 (936, np.float64(0.038291070665157065)),
 (2313, np.float64(0.03824123964007293)),
 (456, np.float64(0.038232700862966186)),
 (781, np.float64(0.03821500273784542)),
 (9, np.float64(0.03819829998478655)),
 (568, np.float64(0.03808971637041946)),
 (896, np.float64(0.038063525727640456)),
 (2301, np.float64(0.037873857107604894)),
 (161, np.float64(0.03786067905138033)),
 (2206, np.float64(0.0377784882789558)),
 (270, np.float64(0.037747034976909885)),
 (863, np.float64(0.037525007585691134)),
 (269, np.float64(0.037524335751799295)),
 (2393, np.float64(0.037297117453084824)),
 (494, np.float64(0.03726685303402451)),
 (2184, np.float64(0.037261619591384736)),
 (283, np.float64(0.037235460477810844)),
 (1763, np.float64(0.03716229922385157)),
 (213, np.float64(0.036935565947333056)),
 (1906, np.float64(0.03691367083708156)),
 (1810, np.float64(0.03684878697109657)),
 (677, np.float64(0.0368112262065656)),
 (539, np.float64(0.03679953345456573)),
 (158, np.float64(0.03674227337602838)),
 (423, np.float64(0.03672440967163138)),
 (696, np.float64(0.03665978288822979)),
 (236, np.float64(0.036621074151722034)),
 (39, np.float64(0.036524747283437436)),
 (1896, np.float64(0.036197723887838755)),
 (2345, np.float64(0.03619722846356041)),
 (436, np.float64(0.036113745256232295)),
 (23, np.float64(0.036053694288392835)),
 (136, np.float64(0.03604818738406314)),
 (654, np.float64(0.03601835710999625)),
 (823, np.float64(0.03592407502572553)),
 (673, np.float64(0.03590713756113148)),
 (1109, np.float64(0.03584862370150463)),
 (752, np.float64(0.035834716168012586)),
 (238, np.float64(0.035738153866531806)),
 (497, np.float64(0.0357260035387577)),
 (1831, np.float64(0.035650868437388045)),
 (322, np.float64(0.03564986167418105)),
 (765, np.float64(0.03561065502286247)),
 (395, np.float64(0.03560188687568909)),
 (596, np.float64(0.03550386102401604)),
 (1868, np.float64(0.03543703177426832)),
 (348, np.float64(0.03543520750145839)),
 (441, np.float64(0.03527287706988264)),
 (830, np.float64(0.03525987914292316)),
 (307, np.float64(0.03524164949628664)),
 (1218, np.float64(0.03522414856166843)),
 (1711, np.float64(0.035103877415420995)),
 (1734, np.float64(0.035037218171280346)),
 (1315, np.float64(0.03500088176968346)),
 (251, np.float64(0.034922621742215734)),
 (1582, np.float64(0.03490431974520328)),
 (2320, np.float64(0.03479976899282934)),
 (1152, np.float64(0.034758712690654704)),
 (1765, np.float64(0.03475854435862824)),
 (301, np.float64(0.03466881538040718)),
 (1984, np.float64(0.03466420382175675)),
 (794, np.float64(0.03465263681369426)),
 (925, np.float64(0.0346227394946056)),
 (439, np.float64(0.034611231912707194)),
 (32, np.float64(0.03451180320672438)),
 (544, np.float64(0.03443122061617495)),
 (2194, np.float64(0.03441881193030967)),
 (1289, np.float64(0.03437173439922231)),
 (1371, np.float64(0.03432960520150024)),
 (2182, np.float64(0.0342003129105442)),
 (702, np.float64(0.03408586791632009)),
 (385, np.float64(0.034012960137878946)),
 (1229, np.float64(0.034012960137878946)),
 (784, np.float64(0.033925772555426045)),
 (932, np.float64(0.033884293225038845)),
 (2376, np.float64(0.033867022459231684)),
 (1112, np.float64(0.0337597923990199)),
 (511, np.float64(0.0336973042611561)),
 (2223, np.float64(0.03366436662498642)),
 (492, np.float64(0.03363967292978037)),
 (329, np.float64(0.03357870002078305)),
 (728, np.float64(0.03357870002078305)),
 (19, np.float64(0.033558691329225024)),
 (218, np.float64(0.03354508713550161)),
 (2386, np.float64(0.033523619546871525)),
 (296, np.float64(0.03351233183687872)),
 (2152, np.float64(0.03348309236964798)),
 (2023, np.float64(0.03337801929259091)),
 (575, np.float64(0.03337041017046399)),
 (2153, np.float64(0.03326631529855422)),
 (2252, np.float64(0.03325487414144111)),
 (1453, np.float64(0.033229836184673914)),
 (819, np.float64(0.03319575859633724)),
 (1813, np.float64(0.03317453068635609)),
 (2275, np.float64(0.03308514553249563)),
 (2113, np.float64(0.033073814379818815)),
 (304, np.float64(0.033005205904425586)),
 (1824, np.float64(0.03291670086406739)),
 (1662, np.float64(0.03288157100528683)),
 (312, np.float64(0.03282425362254923)),
 (291, np.float64(0.03281540133097139)),
 (855, np.float64(0.03268322085129914)),
 (297, np.float64(0.03263248839879191)),
 (1287, np.float64(0.032533449104656637)),
 (186, np.float64(0.03241616307625201)),
 (1117, np.float64(0.032411602071120364)),
 (1318, np.float64(0.03240539709835173)),
 (562, np.float64(0.03236123292621546)),
 (113, np.float64(0.03235493884529431)),
 (1435, np.float64(0.03223183154224267)),
 (518, np.float64(0.032205313278236725)),
 (1519, np.float64(0.0320667640011852)),
 (370, np.float64(0.032048999959860665)),
 (108, np.float64(0.03203640850640195)),
 (252, np.float64(0.031954159750150354)),
 (20, np.float64(0.03195100352365305)),
 (447, np.float64(0.03186077592154149)),
 (919, np.float64(0.03180710226580016)),
 (756, np.float64(0.03167087660874393)),
 (56, np.float64(0.031664934042250244)),
 (2034, np.float64(0.03166190579060936)),
 (99, np.float64(0.031658559223311435)),
 (600, np.float64(0.03164260242062218)),
 (872, np.float64(0.03157691909026507)),
 (397, np.float64(0.03148822493696023)),
 (223, np.float64(0.0314262887308113)),
 (219, np.float64(0.031216287067761497)),
 (993, np.float64(0.03118834245034126)),
 (430, np.float64(0.03114701435466533)),
 (15, np.float64(0.03107435340339451)),
 (620, np.float64(0.031045174666890208)),
 (2052, np.float64(0.031016905149813853)),
 (777, np.float64(0.030908416586742742)),
 (2056, np.float64(0.030861017499659978)),
 (1700, np.float64(0.030852765369009154)),
 (1670, np.float64(0.030834519765007302)),
 (2075, np.float64(0.030819588529952657)),
 (1183, np.float64(0.03080021083457185)),
 (1359, np.float64(0.030751161856860134)),
 (226, np.float64(0.030717188271971077)),
 (740, np.float64(0.030666396513952653)),
 (175, np.float64(0.030661531029015594)),
 (999, np.float64(0.030611212992677467)),
 (216, np.float64(0.030450255352305423)),
 (1420, np.float64(0.030431569389906998)),
 (2071, np.float64(0.03028183519422367)),
 (805, np.float64(0.030221540656264204)),
 (710, np.float64(0.030190880438354342)),
 (535, np.float64(0.03018327519316522)),
 (2203, np.float64(0.030165624216186803)),
 (408, np.float64(0.030152567963799077)),
 (142, np.float64(0.030046319689862325)),
 (412, np.float64(0.030038019432717843)),
 (618, np.float64(0.029963795340421057)),
 (838, np.float64(0.029955007429575693)),
 (482, np.float64(0.029934424801131797)),
 (1100, np.float64(0.029885676792999808)),
 (1052, np.float64(0.029851180736182422)),
 (951, np.float64(0.02979473964724203)),
 (2397, np.float64(0.02976211231109848)),
 (429, np.float64(0.029705381210440487)),
 (881, np.float64(0.029632372947564444)),
 (233, np.float64(0.029526599998630335)),
 (742, np.float64(0.029397708068747506)),
 (1517, np.float64(0.02937171381869879)),
 (695, np.float64(0.029311513541328594)),
 (533, np.float64(0.029249458547730724)),
 (16, np.float64(0.02920381519734453)),
 (1085, np.float64(0.029132013284915912)),
 (330, np.float64(0.02910450269273667)),
 (2196, np.float64(0.029098679607758658)),
 (1134, np.float64(0.02909609366958058)),
 (725, np.float64(0.02900931398122896)),
 (605, np.float64(0.028985259134093135)),
 (1923, np.float64(0.02897612647158648)),
 (757, np.float64(0.028922200451207657)),
 (181, np.float64(0.028597109869660076)),

In [168]:
distance=sorted(list(enumerate(sim[2])),reverse=True,key=lambda x:x[1])
for i in distance[0:5]:
    print(i)
#it also gives us the movie from which we are looking for recommendation we can remove it ...distance[1:6] and then we can print the movie name using index

(2, np.float64(1.0))
(17, np.float64(0.42270488818560925))
(287, np.float64(0.20637643102698372))
(38, np.float64(0.17411871256445144))
(2187, np.float64(0.15608125533549166))

In [169]:
for i in distance[0:6]:
    print(movies.iloc[i[0]].Title)

Spider-Man: Across the Spider-Verse
Spider-Man: Into the Spider-Verse
Spider-Man: Homecoming
Spider-Man: No Way Home
Charlotte's Web
Thor: Ragnarok

In [170]:
def recommend(movie_name):
    movie_index=movies[movies['Title']==movie_name].index[0]
    distance=sorted(list(enumerate(sim[movie_index])),reverse=True, key=lambda x:x[1])
    for i in distance[1:6]:
        print(movies.iloc[i[0]].Title)

In [171]:
recommend('The Dark Knight Rises')

The Dark Knight
The Batman
Joker(I)
Batman Begins
Batman

In [172]:
#pickel used so that we can save our mddel and  reuse it without training the complt model each time
import pickle

In [173]:
#we neeed to save updated_movie dataset & sim_matrix
#pickle.dump(movies,open('movie_list.pkl','wb'))
pickle.dump(sim,open('sim_mtrix.pkl','wb'))

In [174]:
movies.to_csv('movies.csv',index=False)